{% set name = "fastui" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastui-{{ version }}.tar.gz
  sha256: 563d5c37b671bf483f8550f7ff2b3f52857d6382329793698b34258eef7e7c56

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pydantic >=2.5.2

    # Required by pydantic[email]
    - email-validator >=2.0.0

    # Listed as optional but import test needs it anyway
    - fastapi >=0.104
    - python-multipart >=0.0.6

test:
  imports:
    - fastui
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samuelcolvin/FastUI
  summary: Build web application user interfaces defined by declarative Python code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
