{% set name = "fastui" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastui-{{ version }}.tar.gz
  sha256: 08ec1b8437653fc37caaf3dae46566a43dbda3f190c62c43f8f3d063261dd1e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2.5.2

    # Required by pydantic[email]
    - email-validator >=2.0.0

    # Listed as optional but import test needs it anyway
    - fastapi >=0.104
    - python-multipart >=0.0.6

test:
  imports:
    - fastui
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/samuelcolvin/FastUI
  summary: Build web application user interfaces defined by declarative Python code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
